---
- name: downloading installer...
  become: yes
  become_user: root
  get_url: >
    url={{node_n_url}}
    dest=/tmp/n-install.sh
    mode=0755

- name: install...
  become: yes
  become_user: root
  environment:
    N_PREFIX : '{{node_n_prefix}}'
  command: /tmp/n-install.sh -y
  args:
    creates: '{{node_n_prefix}}'

- name: include in path...
  become: yes
  become_user: root
  with_items:
    - etc/profile.d/node-n.sh
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644

- name: install latest npm
  become: yes
  become_user: root
  environment:
    N_PREFIX: '{{node_n_prefix}}'
  command: '{{node_n_prefix}}/bin/npm install -g npm@latest'
